### ISSUE TITLE
jax.js 造成页面大量 meta 跑到 <body> 后面了

### ISSUE THREAD

**Issue by reuixiy** [maple3142/Blog#7]
原因未知，但可以肯定与 jax.js 有关。你的博客目前也有这样的问题，这些 meta 应该是在`<head>`内的，这样导致某些软件（如 Telegram）无法拉取页面预览。考虑过用 gulp 替代，但自己没能解决，冒昧提了个 issue，望见谅。

**Comment by maple3142** [comment]
那不是因為 jax.js 的原因，是 html-minifier 有個選項 renoveOptionalTag

**Comment by reuixiy** [comment]
:joy:，我本地做了大量排除测试，也考虑过你说的原因，将 removeOptionalTag 改为`false`，但并不是。而且，在还没运行 gulp 的情况，结果仍是如此。但将 jax.js 删除后，就正常了，还原后，又有问题了，这就说明就是 jax.js 的问题 :joy: ，你可以本地测试一下。

**Comment by maple3142** [comment]
應該是 https://github.com/pkra/mathjax-node-page 的問題

**Comment by reuixiy** [comment]
谢谢你的回复，我自己解决了哈哈，用 [gulp-mathjax-page](https://github.com/roman-spiridonov/gulp-mathjax-page) 解决了，肥宅快乐水干杯 :cheers: ～
